export enum AppNameService {
  ANALYZE = "ANALYZE",
  CDR = "CDR",
  PROVISIONING2 = "PROVISIONING2",
  USER_ADMIN = "USER_ADMIN",
  SLA = "SLA",
  SYSTEM_ADMIN = "SYSTEM_ADMIN",
  OTHER_ADMIN = "OTHER_ADMIN",
}
