export const DATA_CHART = [
  {
    id: 1,
    targetCode: 'TC001',
    charts: {
      topVisitedSites: [
        { site: 'google.com', visits: 120 },
        { site: 'youtube.com', visits: 95 },
        { site: 'facebook.com', visits: 80 },
        { site: 'twitter.com', visits: 50 },
        { site: 'amazon.com', visits: 40 },
      ],
      topBrowserApps: [
        { browser: 'Chrome', percentage: 65 },
        { browser: 'Safari', percentage: 20 },
        { browser: 'Firefox', percentage: 10 },
        { browser: 'Edge', percentage: 3 },
        { browser: 'Opera', percentage: 2 },
      ],
      topUserAgents: [
        { agent: 'Windows', percentage: 60 },
        { agent: 'MacOS', percentage: 25 },
        { agent: 'Linux', percentage: 10 },
        { agent: 'iOS', percentage: 3 },
        { agent: 'Android', percentage: 2 },
      ],
      protocolUsed: [
        { type: 'HTTP', minutes: 320, percentage: 100 },
        { type: 'HTTPS', minutes: 135, percentage: 74 },
        { type: 'VPN', minutes: 80, percentage: 45 },
      ],
      portUsed: [
        { type: '443 (https)', minutes: 220, percentage: 100 },
        { type: '80 (http)', minutes: 105, percentage: 89 },
        { type: '25 (smfp)', minutes: 55, percentage: 40 },
        { type: '68', minutes: 40, percentage: 18 },
      ],
    },
  },
  {
    id: 2,
    targetCode: 'TC002',
    charts: {
      topVisitedSites: [
        { site: 'bing.com', visits: 100 },
        { site: 'reddit.com', visits: 85 },
        { site: 'linkedin.com', visits: 70 },
        { site: 'instagram.com', visits: 50 },
        { site: 'github.com', visits: 45 },
      ],
      topBrowserApps: [
        { browser: 'Edge', percentage: 40 },
        { browser: 'Chrome', percentage: 35 },
        { browser: 'Safari', percentage: 15 },
        { browser: 'Firefox', percentage: 7 },
        { browser: 'Opera', percentage: 3 },
      ],
      topUserAgents: [
        { agent: 'Windows', percentage: 70 },
        { agent: 'Linux', percentage: 15 },
        { agent: 'MacOS', percentage: 10 },
        { agent: 'Android', percentage: 3 },
        { agent: 'iOS', percentage: 2 },
      ],
      protocolUsed: [
        { type: 'HTTP', minutes: 120, percentage: 100 },
        { type: 'HTTPS', minutes: 35, percentage: 96 },
        { type: 'VPN', minutes: 180, percentage: 66 },
      ],
      portUsed: [
        { type: '443 (https)', minutes: 230, percentage: 100 },
        { type: '80 (http)', minutes: 124, percentage: 47 },
        { type: '25 (smfp)', minutes: 45, percentage: 40 },
        { type: '68', minutes: 41, percentage: 28 },
      ],
    },
  },
  {
    id: 3,
    targetCode: 'TC003',
    charts: {
      topVisitedSites: [
        { site: 'netflix.com', visits: 150 },
        { site: 'hulu.com', visits: 120 },
        { site: 'primevideo.com', visits: 100 },
        { site: 'disneyplus.com', visits: 70 },
        { site: 'youtube.com', visits: 60 },
      ],
      topBrowserApps: [
        { browser: 'Chrome', percentage: 55 },
        { browser: 'Safari', percentage: 25 },
        { browser: 'Firefox', percentage: 10 },
        { browser: 'Edge', percentage: 7 },
        { browser: 'Opera', percentage: 3 },
      ],
      topUserAgents: [
        { agent: 'Windows', percentage: 50 },
        { agent: 'MacOS', percentage: 30 },
        { agent: 'iOS', percentage: 10 },
        { agent: 'Android', percentage: 5 },
        { agent: 'Linux', percentage: 5 },
      ],
      protocolUsed: [
        { type: 'HTTP', minutes: 234, percentage: 100 },
        { type: 'HTTPS', minutes: 190, percentage: 55 },
        { type: 'VPN', minutes: 36, percentage: 12 },
      ],
      portUsed: [
        { type: '443 (https)', minutes: 99, percentage: 100 },
        { type: '80 (http)', minutes: 88, percentage: 54 },
        { type: '25 (smfp)', minutes: 44, percentage: 32 },
        { type: '68', minutes: 33, percentage: 12 },
      ],
    },
  },
  {
    id: 4,
    targetCode: 'TC004',
    charts: {
      topVisitedSites: [
        { site: 'pinterest.com', visits: 110 },
        { site: 'etsy.com', visits: 90 },
        { site: 'walmart.com', visits: 75 },
        { site: 'amazon.com', visits: 60 },
        { site: 'target.com', visits: 50 },
      ],
      topBrowserApps: [
        { browser: 'Safari', percentage: 50 },
        { browser: 'Chrome', percentage: 30 },
        { browser: 'Firefox', percentage: 10 },
        { browser: 'Edge', percentage: 8 },
        { browser: 'Opera', percentage: 2 },
      ],
      topUserAgents: [
        { agent: 'MacOS', percentage: 60 },
        { agent: 'iOS', percentage: 20 },
        { agent: 'Windows', percentage: 10 },
        { agent: 'Android', percentage: 7 },
        { agent: 'Linux', percentage: 3 },
      ],
      protocolUsed: [
        { type: 'HTTP', minutes: 267, percentage: 100 },
        { type: 'HTTPS', minutes: 188, percentage: 78 },
        { type: 'VPN', minutes: 87, percentage: 35 },
      ],
      portUsed: [
        { type: '443 (https)', minutes: 190, percentage: 100 },
        { type: '80 (http)', minutes: 134, percentage: 84 },
        { type: '25 (smfp)', minutes: 127, percentage: 79 },
        { type: '68', minutes: 80, percentage: 65 },
      ],
    },
  },
  {
    id: 5,
    targetCode: 'TC005',
    charts: {
      topVisitedSites: [
        { site: 'stackoverflow.com', visits: 130 },
        { site: 'github.com', visits: 115 },
        { site: 'npmjs.com', visits: 90 },
        { site: 'medium.com', visits: 70 },
        { site: 'dev.to', visits: 60 },
      ],
      topBrowserApps: [
        { browser: 'Chrome', percentage: 75 },
        { browser: 'Firefox', percentage: 15 },
        { browser: 'Edge', percentage: 5 },
        { browser: 'Safari', percentage: 3 },
        { browser: 'Opera', percentage: 2 },
      ],
      topUserAgents: [
        { agent: 'Linux', percentage: 50 },
        { agent: 'Windows', percentage: 30 },
        { agent: 'MacOS', percentage: 15 },
        { agent: 'Android', percentage: 3 },
        { agent: 'iOS', percentage: 2 },
      ],
      protocolUsed: [
        { type: 'HTTP', minutes: 233, percentage: 100 },
        { type: 'HTTPS', minutes: 210, percentage: 87 },
        { type: 'VPN', minutes: 190, percentage: 75 },
      ],
      portUsed: [
        { type: '443 (https)', minutes: 167, percentage: 100 },
        { type: '80 (http)', minutes: 139, percentage: 89 },
        { type: '25 (smfp)', minutes: 120, percentage: 77 },
        { type: '68', minutes: 40, percentage: 66 },
      ],
    },
  },
];
