export const DATA_CHART = [
  {
    id: 1,
    targetCode: 'TC001',
    charts: {
      urlFound: [
        {
          site: 'google.com',
          visits: 120,
          urlItems: [
            'https://www.google.com/favicon.ico',
            'https://www.google.com/search?q=example1',
            'https://www.google.com/search?q=example2',
            'https://www.google.com/search?q=example3',
            'https://www.google.com/search?q=example4',
            'https://www.google.com/search?q=example5',
            'https://www.google.com/search?q=example6',
            'https://www.google.com/search?q=example7',
            'https://www.google.com/search?q=example8',
            'https://www.google.com/search?q=example9',
            'https://www.google.com/search?q=example10',
            'https://www.google.com/search?q=example11',
            'https://www.google.com/search?q=example12',
            'https://www.google.com/search?q=example13',
            'https://www.google.com/search?q=example14',
            'https://www.google.com/search?q=example15',
            'https://www.google.com/search?q=example16',
            'https://www.google.com/search?q=example17',
            'https://www.google.com/search?q=example18',
            'https://www.google.com/search?q=example19',
            'https://www.google.com/search?q=example20',
            'https://www.google.com/search?q=example21',
            'https://www.google.com/search?q=example22',
            'https://www.google.com/search?q=example23',
            'https://www.google.com/search?q=example24',
            'https://www.google.com/search?q=example25',
            'https://www.google.com/search?q=example26',
            'https://www.google.com/search?q=example27',
            'https://www.google.com/search?q=example28',
            'https://www.google.com/search?q=example29',
            'https://www.google.com/search?q=example30',
            'https://www.google.com/search?q=example31',
            'https://www.google.com/search?q=example32',
            'https://www.google.com/search?q=example33',
            'https://www.google.com/search?q=example34',
            'https://www.google.com/search?q=example35',
            'https://www.google.com/search?q=example36',
            'https://www.google.com/search?q=example37',
            'https://www.google.com/search?q=example38',
            'https://www.google.com/search?q=example39',
            'https://www.google.com/search?q=example40',
            'https://www.google.com/search?q=example41',
            'https://www.google.com/search?q=example42',
            'https://www.google.com/search?q=example43',
            'https://www.google.com/search?q=example44',
            'https://www.google.com/search?q=example45',
            'https://www.google.com/search?q=example46',
            'https://www.google.com/search?q=example47',
            'https://www.google.com/search?q=example48',
            'https://www.google.com/search?q=example49',
            'https://www.google.com/search?q=example50',
            'https://www.google.com/search?q=example51',
            'https://www.google.com/search?q=example52',
            'https://www.google.com/search?q=example53',
            'https://www.google.com/search?q=example54',
            'https://www.google.com/search?q=example55',
            'https://www.google.com/search?q=example56',
            'https://www.google.com/search?q=example57',
            'https://www.google.com/search?q=example58',
            'https://www.google.com/search?q=example59',
            'https://www.google.com/search?q=example60',
            'https://www.google.com/search?q=example61',
            'https://www.google.com/search?q=example62',
            'https://www.google.com/search?q=example63',
            'https://www.google.com/search?q=example64',
            'https://www.google.com/search?q=example65',
            'https://www.google.com/search?q=example66',
            'https://www.google.com/search?q=example67',
            'https://www.google.com/search?q=example68',
            'https://www.google.com/search?q=example69',
            'https://www.google.com/search?q=example70',
            'https://www.google.com/search?q=example71',
            'https://www.google.com/search?q=example72',
            'https://www.google.com/search?q=example73',
            'https://www.google.com/search?q=example74',
            'https://www.google.com/search?q=example75',
            'https://www.google.com/search?q=example76',
            'https://www.google.com/search?q=example77',
            'https://www.google.com/search?q=example78',
            'https://www.google.com/search?q=example79',
            'https://www.google.com/search?q=example80',
            'https://www.google.com/search?q=example81',
            'https://www.google.com/search?q=example82',
            'https://www.google.com/search?q=example83',
            'https://www.google.com/search?q=example84',
            'https://www.google.com/search?q=example85',
            'https://www.google.com/search?q=example86',
            'https://www.google.com/search?q=example87',
            'https://www.google.com/search?q=example88',
            'https://www.google.com/search?q=example89',
            'https://www.google.com/search?q=example90',
            'https://www.google.com/search?q=example91',
            'https://www.google.com/search?q=example92',
            'https://www.google.com/search?q=example93',
            'https://www.google.com/search?q=example94',
            'https://www.google.com/search?q=example95',
            'https://www.google.com/search?q=example96',
            'https://www.google.com/search?q=example97',
            'https://www.google.com/search?q=example98',
            'https://www.google.com/search?q=example99',
            'https://www.google.com/search?q=example100',
            'https://www.google.com/search?q=example101',
            'https://www.google.com/search?q=example102',
            'https://www.google.com/search?q=example103',
            'https://www.google.com/search?q=example104',
            'https://www.google.com/search?q=example105',
            'https://www.google.com/search?q=example106',
            'https://www.google.com/search?q=example107',
            'https://www.google.com/search?q=example108',
            'https://www.google.com/search?q=example109',
            'https://www.google.com/search?q=example110',
            'https://www.google.com/search?q=example111',
            'https://www.google.com/search?q=example112',
            'https://www.google.com/search?q=example113',
            'https://www.google.com/search?q=example114',
            'https://www.google.com/search?q=example115',
            'https://www.google.com/search?q=example116',
            'https://www.google.com/search?q=example117',
            'https://www.google.com/search?q=example118',
            'https://www.google.com/search?q=example119',
            'https://www.google.com/search?q=example120',
          ],
        },
        {
          site: 'youtube.com',
          visits: 95,
          urlItems: [
            'https://www.youtube.com/watch?v=video1',
            'https://www.youtube.com/watch?v=video2',
            'https://www.youtube.com/watch?v=video3',
            'https://www.youtube.com/watch?v=video4',
            'https://www.youtube.com/watch?v=video5',
            'https://www.youtube.com/watch?v=video6',
            'https://www.youtube.com/watch?v=video7',
            'https://www.youtube.com/watch?v=video8',
            'https://www.youtube.com/watch?v=video9',
            'https://www.youtube.com/watch?v=video10',
            'https://www.youtube.com/watch?v=video11',
            'https://www.youtube.com/watch?v=video12',
            'https://www.youtube.com/watch?v=video13',
            'https://www.youtube.com/watch?v=video14',
            'https://www.youtube.com/watch?v=video15',
            'https://www.youtube.com/watch?v=video16',
            'https://www.youtube.com/watch?v=video17',
            'https://www.youtube.com/watch?v=video18',
            'https://www.youtube.com/watch?v=video19',
            'https://www.youtube.com/watch?v=video20',
            'https://www.youtube.com/watch?v=video21',
            'https://www.youtube.com/watch?v=video22',
            'https://www.youtube.com/watch?v=video23',
            'https://www.youtube.com/watch?v=video24',
            'https://www.youtube.com/watch?v=video25',
            'https://www.youtube.com/watch?v=video26',
            'https://www.youtube.com/watch?v=video27',
            'https://www.youtube.com/watch?v=video28',
            'https://www.youtube.com/watch?v=video29',
            'https://www.youtube.com/watch?v=video30',
            'https://www.youtube.com/watch?v=video31',
            'https://www.youtube.com/watch?v=video32',
            'https://www.youtube.com/watch?v=video33',
            'https://www.youtube.com/watch?v=video34',
            'https://www.youtube.com/watch?v=video35',
            'https://www.youtube.com/watch?v=video36',
            'https://www.youtube.com/watch?v=video37',
            'https://www.youtube.com/watch?v=video38',
            'https://www.youtube.com/watch?v=video39',
            'https://www.youtube.com/watch?v=video40',
            'https://www.youtube.com/watch?v=video41',
            'https://www.youtube.com/watch?v=video42',
            'https://www.youtube.com/watch?v=video43',
            'https://www.youtube.com/watch?v=video44',
            'https://www.youtube.com/watch?v=video45',
            'https://www.youtube.com/watch?v=video46',
            'https://www.youtube.com/watch?v=video47',
            'https://www.youtube.com/watch?v=video48',
            'https://www.youtube.com/watch?v=video49',
            'https://www.youtube.com/watch?v=video50',
            'https://www.youtube.com/watch?v=video51',
            'https://www.youtube.com/watch?v=video52',
            'https://www.youtube.com/watch?v=video53',
            'https://www.youtube.com/watch?v=video54',
            'https://www.youtube.com/watch?v=video55',
            'https://www.youtube.com/watch?v=video56',
            'https://www.youtube.com/watch?v=video57',
            'https://www.youtube.com/watch?v=video58',
            'https://www.youtube.com/watch?v=video59',
            'https://www.youtube.com/watch?v=video60',
            'https://www.youtube.com/watch?v=video61',
            'https://www.youtube.com/watch?v=video62',
            'https://www.youtube.com/watch?v=video63',
            'https://www.youtube.com/watch?v=video64',
            'https://www.youtube.com/watch?v=video65',
            'https://www.youtube.com/watch?v=video66',
            'https://www.youtube.com/watch?v=video67',
            'https://www.youtube.com/watch?v=video68',
            'https://www.youtube.com/watch?v=video69',
            'https://www.youtube.com/watch?v=video70',
            'https://www.youtube.com/watch?v=video71',
            'https://www.youtube.com/watch?v=video72',
            'https://www.youtube.com/watch?v=video73',
            'https://www.youtube.com/watch?v=video74',
            'https://www.youtube.com/watch?v=video75',
            'https://www.youtube.com/watch?v=video76',
            'https://www.youtube.com/watch?v=video77',
            'https://www.youtube.com/watch?v=video78',
            'https://www.youtube.com/watch?v=video79',
            'https://www.youtube.com/watch?v=video80',
            'https://www.youtube.com/watch?v=video81',
            'https://www.youtube.com/watch?v=video82',
            'https://www.youtube.com/watch?v=video83',
            'https://www.youtube.com/watch?v=video84',
            'https://www.youtube.com/watch?v=video85',
            'https://www.youtube.com/watch?v=video86',
            'https://www.youtube.com/watch?v=video87',
            'https://www.youtube.com/watch?v=video88',
            'https://www.youtube.com/watch?v=video89',
            'https://www.youtube.com/watch?v=video90',
            'https://www.youtube.com/watch?v=video91',
            'https://www.youtube.com/watch?v=video92',
            'https://www.youtube.com/watch?v=video93',
            'https://www.youtube.com/watch?v=video94',
            'https://www.youtube.com/watch?v=video95',
          ],
        },
        {
          site: 'facebook.com',
          visits: 80,
          urlItems: [
            'https://www.facebook.com/profile1',
            'https://www.facebook.com/profile2',
            'https://www.facebook.com/profile3',
            'https://www.facebook.com/profile4',
            'https://www.facebook.com/profile5',
            'https://www.facebook.com/profile6',
            'https://www.facebook.com/profile7',
            'https://www.facebook.com/profile8',
            'https://www.facebook.com/profile9',
            'https://www.facebook.com/profile10',
            'https://www.facebook.com/profile11',
            'https://www.facebook.com/profile12',
            'https://www.facebook.com/profile13',
            'https://www.facebook.com/profile14',
            'https://www.facebook.com/profile15',
            'https://www.facebook.com/profile16',
            'https://www.facebook.com/profile17',
            'https://www.facebook.com/profile18',
            'https://www.facebook.com/profile19',
            'https://www.facebook.com/profile20',
            'https://www.facebook.com/profile21',
            'https://www.facebook.com/profile22',
            'https://www.facebook.com/profile23',
            'https://www.facebook.com/profile24',
            'https://www.facebook.com/profile25',
            'https://www.facebook.com/profile26',
            'https://www.facebook.com/profile27',
            'https://www.facebook.com/profile28',
            'https://www.facebook.com/profile29',
            'https://www.facebook.com/profile30',
            'https://www.facebook.com/profile31',
            'https://www.facebook.com/profile32',
            'https://www.facebook.com/profile33',
            'https://www.facebook.com/profile34',
            'https://www.facebook.com/profile35',
            'https://www.facebook.com/profile36',
            'https://www.facebook.com/profile37',
            'https://www.facebook.com/profile38',
            'https://www.facebook.com/profile39',
            'https://www.facebook.com/profile40',
            'https://www.facebook.com/profile41',
            'https://www.facebook.com/profile42',
            'https://www.facebook.com/profile43',
            'https://www.facebook.com/profile44',
            'https://www.facebook.com/profile45',
            'https://www.facebook.com/profile46',
            'https://www.facebook.com/profile47',
            'https://www.facebook.com/profile48',
            'https://www.facebook.com/profile49',
            'https://www.facebook.com/profile50',
            'https://www.facebook.com/profile51',
            'https://www.facebook.com/profile52',
            'https://www.facebook.com/profile53',
            'https://www.facebook.com/profile54',
            'https://www.facebook.com/profile55',
            'https://www.facebook.com/profile56',
            'https://www.facebook.com/profile57',
            'https://www.facebook.com/profile58',
            'https://www.facebook.com/profile59',
            'https://www.facebook.com/profile60',
            'https://www.facebook.com/profile61',
            'https://www.facebook.com/profile62',
            'https://www.facebook.com/profile63',
            'https://www.facebook.com/profile64',
            'https://www.facebook.com/profile65',
            'https://www.facebook.com/profile66',
            'https://www.facebook.com/profile67',
            'https://www.facebook.com/profile68',
            'https://www.facebook.com/profile69',
            'https://www.facebook.com/profile70',
            'https://www.facebook.com/profile71',
            'https://www.facebook.com/profile72',
            'https://www.facebook.com/profile73',
            'https://www.facebook.com/profile74',
            'https://www.facebook.com/profile75',
            'https://www.facebook.com/profile76',
            'https://www.facebook.com/profile77',
            'https://www.facebook.com/profile78',
            'https://www.facebook.com/profile79',
            'https://www.facebook.com/profile80',
          ],
        },
        {
          site: 'twitter.com',
          visits: 50,
          urlItems: [
            'https://twitter.com/status1',
            'https://twitter.com/status2',
            'https://twitter.com/status3',
            'https://twitter.com/status4',
            'https://twitter.com/status5',
            'https://twitter.com/status6',
            'https://twitter.com/status7',
            'https://twitter.com/status8',
            'https://twitter.com/status9',
            'https://twitter.com/status10',
            'https://twitter.com/status11',
            'https://twitter.com/status12',
            'https://twitter.com/status13',
            'https://twitter.com/status14',
            'https://twitter.com/status15',
            'https://twitter.com/status16',
            'https://twitter.com/status17',
            'https://twitter.com/status18',
            'https://twitter.com/status19',
            'https://twitter.com/status20',
            'https://twitter.com/status21',
            'https://twitter.com/status22',
            'https://twitter.com/status23',
            'https://twitter.com/status24',
            'https://twitter.com/status25',
            'https://twitter.com/status26',
            'https://twitter.com/status27',
            'https://twitter.com/status28',
            'https://twitter.com/status29',
            'https://twitter.com/status30',
            'https://twitter.com/status31',
            'https://twitter.com/status32',
            'https://twitter.com/status33',
            'https://twitter.com/status34',
            'https://twitter.com/status35',
            'https://twitter.com/status36',
            'https://twitter.com/status37',
            'https://twitter.com/status38',
            'https://twitter.com/status39',
            'https://twitter.com/status40',
            'https://twitter.com/status41',
            'https://twitter.com/status42',
            'https://twitter.com/status43',
            'https://twitter.com/status44',
            'https://twitter.com/status45',
            'https://twitter.com/status46',
            'https://twitter.com/status47',
            'https://twitter.com/status48',
            'https://twitter.com/status49',
            'https://twitter.com/status50',
          ],
        },
        {
          site: 'amazon.com',
          visits: 40,
          urlItems: [
            'https://www.amazon.com/product1',
            'https://www.amazon.com/product2',
            'https://www.amazon.com/product3',
            'https://www.amazon.com/product4',
            'https://www.amazon.com/product5',
            'https://www.amazon.com/product6',
            'https://www.amazon.com/product7',
            'https://www.amazon.com/product8',
            'https://www.amazon.com/product9',
            'https://www.amazon.com/product10',
            'https://www.amazon.com/product11',
            'https://www.amazon.com/product12',
            'https://www.amazon.com/product13',
            'https://www.amazon.com/product14',
            'https://www.amazon.com/product15',
            'https://www.amazon.com/product16',
            'https://www.amazon.com/product17',
            'https://www.amazon.com/product18',
            'https://www.amazon.com/product19',
            'https://www.amazon.com/product20',
            'https://www.amazon.com/product21',
            'https://www.amazon.com/product22',
            'https://www.amazon.com/product23',
            'https://www.amazon.com/product24',
            'https://www.amazon.com/product25',
            'https://www.amazon.com/product26',
            'https://www.amazon.com/product27',
            'https://www.amazon.com/product28',
            'https://www.amazon.com/product29',
            'https://www.amazon.com/product30',
            'https://www.amazon.com/product31',
            'https://www.amazon.com/product32',
            'https://www.amazon.com/product33',
            'https://www.amazon.com/product34',
            'https://www.amazon.com/product35',
            'https://www.amazon.com/product36',
            'https://www.amazon.com/product37',
            'https://www.amazon.com/product38',
            'https://www.amazon.com/product39',
            'https://www.amazon.com/product40',
          ],
        },
      ],
      browserApps: [
        { browser: 'Chrome', percentage: 65 },
        { browser: 'Safari', percentage: 20 },
        { browser: 'Firefox', percentage: 10 },
        { browser: 'Edge', percentage: 3 },
        { browser: 'Opera', percentage: 2 },
      ],
      userAgents: [
        {
          agent: 'macintosh; intel mac os x 10_15_7;mozilla/5.0',
          percentage: 50,
        },
        {
          agent: 'xll; ubuntu; linux x86_64; rv:85.0;mozilla/5.0',
          percentage: 30,
        },
      ],
      uniqueIP: [
        { source: '8.8.8.8', destination: '10.0.0.0' },
        { source: '10.0.0.8', destination: '10.0.0.0' },
        { source: '8.8.4.4', destination: '10.0.0.0' },
        { source: '8.8.4.4', destination: '10.0.0.0' },
        { source: '8.8.4.4', destination: '1.1.1.1' },
      ],
      dns: [
        { name: '_airplay_tcp_local', value: 5 },
        { name: '_sample_tcp_local', value: 5 },
        { name: '_riot_tcp_local', value: 4 },
        { name: '_kid_tcp_local', value: 2 },
        { name: '_vase_tcp_local', value: 2 },
        { name: 'mail.example.com', value: 2 },
      ],
      protocolUsed: [
        { type: 'HTTP', minutes: 320, percentage: 100 },
        { type: 'HTTPS', minutes: 135, percentage: 74 },
        { type: 'VPN', minutes: 80, percentage: 45 },
      ],
      portUsed: [
        { type: '443 (https)', minutes: 220, percentage: 100 },
        { type: '80 (http)', minutes: 105, percentage: 89 },
        { type: '25 (smfp)', minutes: 55, percentage: 40 },
        { type: '22 (ssh)', minutes: 40, percentage: 10 },
        { type: '68', minutes: 40, percentage: 18 },
      ],
    },
  },
  {
    id: 2,
    targetCode: 'TC002',
    charts: {
      urlFound: [
        {
          site: 'bing.com',
          visits: 30,
          urlItems: [
            'https://www.bing.com/favicon.ico',
            'https://www.bing.com/search?q=example1',
            'https://www.bing.com/search?q=example2',
            'https://www.bing.com/search?q=example3',
            'https://www.bing.com/search?q=example4',
            'https://www.bing.com/search?q=example5',
            'https://www.bing.com/search?q=example6',
            'https://www.bing.com/search?q=example7',
            'https://www.bing.com/search?q=example8',
            'https://www.bing.com/search?q=example9',
            'https://www.bing.com/search?q=example10',
            'https://www.bing.com/search?q=example11',
            'https://www.bing.com/search?q=example12',
            'https://www.bing.com/search?q=example13',
            'https://www.bing.com/search?q=example14',
            'https://www.bing.com/search?q=example15',
            'https://www.bing.com/search?q=example16',
            'https://www.bing.com/search?q=example17',
            'https://www.bing.com/search?q=example18',
            'https://www.bing.com/search?q=example19',
            'https://www.bing.com/search?q=example20',
            'https://www.bing.com/search?q=example21',
            'https://www.bing.com/search?q=example22',
            'https://www.bing.com/search?q=example23',
            'https://www.bing.com/search?q=example24',
            'https://www.bing.com/search?q=example25',
            'https://www.bing.com/search?q=example26',
            'https://www.bing.com/search?q=example27',
            'https://www.bing.com/search?q=example28',
            'https://www.bing.com/search?q=example29',
            'https://www.bing.com/search?q=example30',
          ],
        },
        {
          site: 'reddit.com',
          visits: 10,
          urlItems: [
            'https://www.reddit.com/r/example1',
            'https://www.reddit.com/r/example2',
            'https://www.reddit.com/r/example3',
            'https://www.reddit.com/r/example4',
            'https://www.reddit.com/r/example5',
            'https://www.reddit.com/r/example6',
            'https://www.reddit.com/r/example7',
            'https://www.reddit.com/r/example8',
            'https://www.reddit.com/r/example9',
            'https://www.reddit.com/r/example10',
          ],
        },
        {
          site: 'linkedin.com',
          visits: 8,
          urlItems: [
            'https://www.linkedin.com/in/profile1',
            'https://www.linkedin.com/in/profile2',
            'https://www.linkedin.com/in/profile3',
            'https://www.linkedin.com/in/profile4',
            'https://www.linkedin.com/in/profile5',
            'https://www.linkedin.com/in/profile6',
            'https://www.linkedin.com/in/profile7',
            'https://www.linkedin.com/in/profile8',
          ],
        },
        {
          site: 'instagram.com',
          visits: 2,
          urlItems: [
            'https://www.instagram.com/p/example1',
            'https://www.instagram.com/p/example2',
          ],
        },
        {
          site: 'github.com',
          visits: 1,
          urlItems: ['https://www.github.com/repository1'],
        },
      ],
      browserApps: [
        { browser: 'Edge', percentage: 40 },
        { browser: 'Chrome', percentage: 35 },
        { browser: 'Safari', percentage: 15 },
        { browser: 'Firefox', percentage: 7 },
        { browser: 'Opera', percentage: 3 },
      ],
      userAgents: [
        {
          agent: 'macintosh; intel mac os x 10_15_7;mozilla/5.0',
          percentage: 50,
        },
        {
          agent: 'xll; ubuntu; linux x86_64; rv:85.0;mozilla/5.0',
          percentage: 30,
        },
      ],
      uniqueIP: [
        { source: '8.8.8.8', destination: '10.0.0.0' },
        { source: '10.0.0.8', destination: '10.0.0.0' },
        { source: '8.8.4.4', destination: '10.0.0.0' },
        { source: '8.8.4.4', destination: '10.0.0.0' },
        { source: '8.8.4.4', destination: '1.1.1.1' },
      ],
      dns: [
        { name: '_airplay_tcp_local', value: 5 },
        { name: '_sample_tcp_local', value: 5 },
        { name: '_riot_tcp_local', value: 4 },
        { name: '_kid_tcp_local', value: 2 },
        { name: '_vase_tcp_local', value: 2 },
        { name: 'mail.example.com', value: 2 },
      ],
      protocolUsed: [
        { type: 'HTTP', minutes: 120, percentage: 100 },
        { type: 'HTTPS', minutes: 35, percentage: 96 },
        { type: 'VPN', minutes: 180, percentage: 66 },
      ],
      portUsed: [
        { type: '443 (https)', minutes: 230, percentage: 100 },
        { type: '80 (http)', minutes: 124, percentage: 47 },
        { type: '25 (smfp)', minutes: 45, percentage: 40 },
        { type: '68', minutes: 41, percentage: 28 },
      ],
    },
  },
  {
    id: 3,
    targetCode: 'TC003',
    charts: {
      urlFound: [
        {
          site: 'netflix.com',
          visits: 3,
          urlItems: [
            'https://www.netflix.com/watch/episode1',
            'https://www.netflix.com/watch/episode2',
            'https://www.netflix.com/watch/episode3',
          ],
        },
        {
          site: 'primevideo.com',
          visits: 2,
          urlItems: [
            'https://www.primevideo.com/watch/episode1',
            'https://www.primevideo.com/watch/episode2',
          ],
        },
        {
          site: 'youtube.com',
          visits: 1,
          urlItems: ['https://www.youtube.com/watch?v=video1'],
        },
      ],
      browserApps: [
        { browser: 'Chrome', percentage: 55 },
        { browser: 'Safari', percentage: 25 },
        { browser: 'Firefox', percentage: 10 },
        { browser: 'Edge', percentage: 7 },
        { browser: 'Opera', percentage: 3 },
      ],
      userAgents: [
        {
          agent: 'macintosh; intel mac os x 10_15_7;mozilla/5.0',
          percentage: 50,
        },
        {
          agent: 'xll; ubuntu; linux x86_64; rv:85.0;mozilla/5.0',
          percentage: 30,
        },
      ],
      uniqueIP: [
        { source: '8.8.8.8', destination: '10.0.0.0' },
        { source: '10.0.0.8', destination: '10.0.0.0' },
        { source: '8.8.4.4', destination: '10.0.0.0' },
        { source: '8.8.4.4', destination: '10.0.0.0' },
        { source: '8.8.4.4', destination: '1.1.1.1' },
      ],
      dns: [
        { name: '_airplay_tcp_local', value: 5 },
        { name: '_sample_tcp_local', value: 5 },
        { name: '_riot_tcp_local', value: 4 },
        { name: '_kid_tcp_local', value: 2 },
        { name: '_vase_tcp_local', value: 2 },
        { name: 'mail.example.com', value: 2 },
      ],
      protocolUsed: [
        { type: 'HTTP', minutes: 234, percentage: 100 },
        { type: 'HTTPS', minutes: 190, percentage: 55 },
        { type: 'VPN', minutes: 36, percentage: 12 },
      ],
      portUsed: [
        { type: '443 (https)', minutes: 99, percentage: 100 },
        { type: '80 (http)', minutes: 88, percentage: 54 },
        { type: '25 (smfp)', minutes: 44, percentage: 32 },
        { type: '68', minutes: 33, percentage: 12 },
      ],
    },
  },
  {
    id: 4,
    targetCode: 'TC004',
    charts: {
      urlFound: [
        {
          site: 'pinterest.com',
          visits: 12,
          urlItems: [
            'https://www.pinterest.com/pin/1',
            'https://www.pinterest.com/pin/2',
            'https://www.pinterest.com/pin/3',
            'https://www.pinterest.com/pin/4',
            'https://www.pinterest.com/pin/5',
            'https://www.pinterest.com/pin/6',
            'https://www.pinterest.com/pin/7',
            'https://www.pinterest.com/pin/8',
            'https://www.pinterest.com/pin/9',
            'https://www.pinterest.com/pin/10',
            'https://www.pinterest.com/pin/11',
            'https://www.pinterest.com/pin/12',
          ],
        },
        {
          site: 'walmart.com',
          visits: 8,
          urlItems: [
            'https://www.walmart.com/product/1',
            'https://www.walmart.com/product/2',
            'https://www.walmart.com/product/3',
            'https://www.walmart.com/product/4',
            'https://www.walmart.com/product/5',
            'https://www.walmart.com/product/6',
            'https://www.walmart.com/product/7',
            'https://www.walmart.com/product/8',
          ],
        },
        {
          site: 'amazon.com',
          visits: 3,
          urlItems: [
            'https://www.amazon.com/product/1',
            'https://www.amazon.com/product/2',
            'https://www.amazon.com/product/3',
          ],
        },
        {
          site: 'target.com',
          visits: 1,
          urlItems: ['https://www.target.com/product/1'],
        },
      ],
      browserApps: [
        { browser: 'Safari', percentage: 50 },
        { browser: 'Chrome', percentage: 30 },
        { browser: 'Firefox', percentage: 10 },
        { browser: 'Edge', percentage: 8 },
        { browser: 'Opera', percentage: 2 },
      ],
      userAgents: [
        {
          agent: 'macintosh; intel mac os x 10_15_7;mozilla/5.0',
          percentage: 50,
        },
        {
          agent: 'xll; ubuntu; linux x86_64; rv:85.0;mozilla/5.0',
          percentage: 30,
        },
      ],
      uniqueIP: [
        { source: '8.8.8.8', destination: '10.0.0.0' },
        { source: '10.0.0.8', destination: '10.0.0.0' },
        { source: '8.8.4.4', destination: '10.0.0.0' },
        { source: '8.8.4.4', destination: '10.0.0.0' },
        { source: '8.8.4.4', destination: '1.1.1.1' },
      ],
      dns: [
        { name: '_airplay_tcp_local', value: 5 },
        { name: '_sample_tcp_local', value: 5 },
        { name: '_riot_tcp_local', value: 4 },
        { name: '_kid_tcp_local', value: 2 },
        { name: '_vase_tcp_local', value: 2 },
        { name: 'mail.example.com', value: 2 },
      ],
      protocolUsed: [
        { type: 'HTTP', minutes: 267, percentage: 100 },
        { type: 'HTTPS', minutes: 188, percentage: 78 },
        { type: 'VPN', minutes: 87, percentage: 35 },
      ],
      portUsed: [
        { type: '443 (https)', minutes: 190, percentage: 100 },
        { type: '80 (http)', minutes: 134, percentage: 84 },
        { type: '25 (smfp)', minutes: 127, percentage: 79 },
        { type: '68', minutes: 80, percentage: 65 },
      ],
    },
  },
  {
    id: 5,
    targetCode: 'TC005',
    charts: {
      urlFound: [
        {
          site: 'stackoverflow.com',
          visits: 44,
          urlItems: [
            'https://stackoverflow.com/questions/1',
            'https://stackoverflow.com/questions/2',
            'https://stackoverflow.com/questions/3',
            'https://stackoverflow.com/questions/4',
            'https://stackoverflow.com/questions/5',
            'https://stackoverflow.com/questions/6',
            'https://stackoverflow.com/questions/7',
            'https://stackoverflow.com/questions/8',
            'https://stackoverflow.com/questions/9',
            'https://stackoverflow.com/questions/10',
            'https://stackoverflow.com/questions/11',
            'https://stackoverflow.com/questions/12',
            'https://stackoverflow.com/questions/13',
            'https://stackoverflow.com/questions/14',
            'https://stackoverflow.com/questions/15',
            'https://stackoverflow.com/questions/16',
            'https://stackoverflow.com/questions/17',
            'https://stackoverflow.com/questions/18',
            'https://stackoverflow.com/questions/19',
            'https://stackoverflow.com/questions/20',
            'https://stackoverflow.com/questions/21',
            'https://stackoverflow.com/questions/22',
            'https://stackoverflow.com/questions/23',
            'https://stackoverflow.com/questions/24',
            'https://stackoverflow.com/questions/25',
            'https://stackoverflow.com/questions/26',
            'https://stackoverflow.com/questions/27',
            'https://stackoverflow.com/questions/28',
            'https://stackoverflow.com/questions/29',
            'https://stackoverflow.com/questions/30',
            'https://stackoverflow.com/questions/31',
            'https://stackoverflow.com/questions/32',
            'https://stackoverflow.com/questions/33',
            'https://stackoverflow.com/questions/34',
            'https://stackoverflow.com/questions/35',
            'https://stackoverflow.com/questions/36',
            'https://stackoverflow.com/questions/37',
            'https://stackoverflow.com/questions/38',
            'https://stackoverflow.com/questions/39',
            'https://stackoverflow.com/questions/40',
            'https://stackoverflow.com/questions/41',
            'https://stackoverflow.com/questions/42',
            'https://stackoverflow.com/questions/43',
            'https://stackoverflow.com/questions/44',
          ],
        },
        {
          site: 'github.com',
          visits: 34,
          urlItems: [
            'https://github.com/repo/1',
            'https://github.com/repo/2',
            'https://github.com/repo/3',
            'https://github.com/repo/4',
            'https://github.com/repo/5',
            'https://github.com/repo/6',
            'https://github.com/repo/7',
            'https://github.com/repo/8',
            'https://github.com/repo/9',
            'https://github.com/repo/10',
            'https://github.com/repo/11',
            'https://github.com/repo/12',
            'https://github.com/repo/13',
            'https://github.com/repo/14',
            'https://github.com/repo/15',
            'https://github.com/repo/16',
            'https://github.com/repo/17',
            'https://github.com/repo/18',
            'https://github.com/repo/19',
            'https://github.com/repo/20',
            'https://github.com/repo/21',
            'https://github.com/repo/22',
            'https://github.com/repo/23',
            'https://github.com/repo/24',
            'https://github.com/repo/25',
            'https://github.com/repo/26',
            'https://github.com/repo/27',
            'https://github.com/repo/28',
            'https://github.com/repo/29',
            'https://github.com/repo/30',
            'https://github.com/repo/31',
            'https://github.com/repo/32',
            'https://github.com/repo/33',
            'https://github.com/repo/34',
          ],
        },
        {
          site: 'npmjs.com',
          visits: 24,
          urlItems: [
            'https://www.npmjs.com/package/package1',
            'https://www.npmjs.com/package/package2',
            'https://www.npmjs.com/package/package3',
            'https://www.npmjs.com/package/package4',
            'https://www.npmjs.com/package/package5',
            'https://www.npmjs.com/package/package6',
            'https://www.npmjs.com/package/package7',
            'https://www.npmjs.com/package/package8',
            'https://www.npmjs.com/package/package9',
            'https://www.npmjs.com/package/package10',
            'https://www.npmjs.com/package/package11',
            'https://www.npmjs.com/package/package12',
            'https://www.npmjs.com/package/package13',
            'https://www.npmjs.com/package/package14',
            'https://www.npmjs.com/package/package15',
            'https://www.npmjs.com/package/package16',
            'https://www.npmjs.com/package/package17',
            'https://www.npmjs.com/package/package18',
            'https://www.npmjs.com/package/package19',
            'https://www.npmjs.com/package/package20',
            'https://www.npmjs.com/package/package21',
            'https://www.npmjs.com/package/package22',
            'https://www.npmjs.com/package/package23',
            'https://www.npmjs.com/package/package24',
          ],
        },
        {
          site: 'medium.com',
          visits: 14,
          urlItems: [
            'https://medium.com/article/1',
            'https://medium.com/article/2',
            'https://medium.com/article/3',
            'https://medium.com/article/4',
            'https://medium.com/article/5',
            'https://medium.com/article/6',
            'https://medium.com/article/7',
            'https://medium.com/article/8',
            'https://medium.com/article/9',
            'https://medium.com/article/10',
            'https://medium.com/article/11',
            'https://medium.com/article/12',
            'https://medium.com/article/13',
            'https://medium.com/article/14',
          ],
        },
        {
          site: 'dev.to',
          visits: 4,
          urlItems: [
            'https://dev.to/post/1',
            'https://dev.to/post/2',
            'https://dev.to/post/3',
            'https://dev.to/post/4',
          ],
        },
      ],
      browserApps: [
        { browser: 'Chrome', percentage: 75 },
        { browser: 'Firefox', percentage: 15 },
        { browser: 'Edge', percentage: 5 },
        { browser: 'Safari', percentage: 3 },
        { browser: 'Opera', percentage: 2 },
      ],
      userAgents: [
        {
          agent: 'macintosh; intel mac os x 10_15_7;mozilla/5.0',
          percentage: 50,
        },
        {
          agent: 'xll; ubuntu; linux x86_64; rv:85.0;mozilla/5.0',
          percentage: 30,
        },
      ],
      uniqueIP: [
        { source: '8.8.8.8', destination: '10.0.0.0' },
        { source: '10.0.0.8', destination: '10.0.0.0' },
        { source: '8.8.4.4', destination: '10.0.0.0' },
        { source: '8.8.4.4', destination: '10.0.0.0' },
        { source: '8.8.4.4', destination: '1.1.1.1' },
      ],
      dns: [
        { name: '_airplay_tcp_local', value: 5 },
        { name: '_sample_tcp_local', value: 5 },
        { name: '_riot_tcp_local', value: 4 },
        { name: '_kid_tcp_local', value: 2 },
        { name: '_vase_tcp_local', value: 2 },
        { name: 'mail.example.com', value: 2 },
      ],
      protocolUsed: [
        { type: 'HTTP', minutes: 233, percentage: 100 },
        { type: 'HTTPS', minutes: 210, percentage: 87 },
        { type: 'VPN', minutes: 190, percentage: 75 },
      ],
      portUsed: [
        { type: '443 (https)', minutes: 167, percentage: 100 },
        { type: '80 (http)', minutes: 139, percentage: 89 },
        { type: '25 (smfp)', minutes: 120, percentage: 77 },
        { type: '68', minutes: 40, percentage: 66 },
      ],
    },
  },
];
